services:
  - type: web
    name: timehaven-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OUTLOOK_CLIENT_ID
        sync: false
      - key: OUTLOOK_CLIENT_SECRET
        sync: false